# Generated by Django 5.1.3 on 2024-11-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appname', models.CharField(max_length=100)),
                ('applink', models.URLField()),
                ('category1', models.CharField(choices=[('Technology', 'Technology'), ('Health', 'Health'), ('Education', 'Education'), ('Food', 'Food')], max_length=50)),
                ('category2', models.CharField(choices=[('Software', 'Software'), ('Hardware', 'Hardware'), ('Service', 'Service')], max_length=50)),
                ('add_points', models.IntegerField()),
            ],
        ),
    ]
